/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReimbursementsRouteImport } from './routes/reimbursements'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferenceDataRouteImport } from './routes/reference-data'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiagnosesRouteImport } from './routes/diagnoses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyTypesRouteImport } from './routes/company-types'
import { Route as CompanyGroupsRouteImport } from './routes/company-groups'
import { Route as CompanyBranchesRouteImport } from './routes/company-branches'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ClaimPaymentsRouteImport } from './routes/claim-payments'
import { Route as CardReplacementsRouteImport } from './routes/card-replacements'
import { Route as BillingSessionsRouteImport } from './routes/billing-sessions'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReimbursementsRoute = ReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceDataRoute = ReferenceDataRouteImport.update({
  id: '/reference-data',
  path: '/reference-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosesRoute = DiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTypesRoute = CompanyTypesRouteImport.update({
  id: '/company-types',
  path: '/company-types',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyGroupsRoute = CompanyGroupsRouteImport.update({
  id: '/company-groups',
  path: '/company-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyBranchesRoute = CompanyBranchesRouteImport.update({
  id: '/company-branches',
  path: '/company-branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimPaymentsRoute = ClaimPaymentsRouteImport.update({
  id: '/claim-payments',
  path: '/claim-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CardReplacementsRoute = CardReplacementsRouteImport.update({
  id: '/card-replacements',
  path: '/card-replacements',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSessionsRoute = BillingSessionsRouteImport.update({
  id: '/billing-sessions',
  path: '/billing-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/billing-sessions': typeof BillingSessionsRoute
  '/card-replacements': typeof CardReplacementsRoute
  '/claim-payments': typeof ClaimPaymentsRoute
  '/claims': typeof ClaimsRoute
  '/companies': typeof CompaniesRoute
  '/company-branches': typeof CompanyBranchesRoute
  '/company-groups': typeof CompanyGroupsRoute
  '/company-types': typeof CompanyTypesRoute
  '/dashboard': typeof DashboardRoute
  '/diagnoses': typeof DiagnosesRoute
  '/docs': typeof DocsRoute
  '/doctors': typeof DoctorsRoute
  '/health': typeof HealthRoute
  '/hospitals': typeof HospitalsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/members': typeof MembersRoute
  '/reference-data': typeof ReferenceDataRoute
  '/register': typeof RegisterRoute
  '/reimbursements': typeof ReimbursementsRoute
  '/reports': typeof ReportsRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/tenants': typeof TenantsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/billing-sessions': typeof BillingSessionsRoute
  '/card-replacements': typeof CardReplacementsRoute
  '/claim-payments': typeof ClaimPaymentsRoute
  '/claims': typeof ClaimsRoute
  '/companies': typeof CompaniesRoute
  '/company-branches': typeof CompanyBranchesRoute
  '/company-groups': typeof CompanyGroupsRoute
  '/company-types': typeof CompanyTypesRoute
  '/dashboard': typeof DashboardRoute
  '/diagnoses': typeof DiagnosesRoute
  '/docs': typeof DocsRoute
  '/doctors': typeof DoctorsRoute
  '/health': typeof HealthRoute
  '/hospitals': typeof HospitalsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/members': typeof MembersRoute
  '/reference-data': typeof ReferenceDataRoute
  '/register': typeof RegisterRoute
  '/reimbursements': typeof ReimbursementsRoute
  '/reports': typeof ReportsRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/tenants': typeof TenantsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/billing-sessions': typeof BillingSessionsRoute
  '/card-replacements': typeof CardReplacementsRoute
  '/claim-payments': typeof ClaimPaymentsRoute
  '/claims': typeof ClaimsRoute
  '/companies': typeof CompaniesRoute
  '/company-branches': typeof CompanyBranchesRoute
  '/company-groups': typeof CompanyGroupsRoute
  '/company-types': typeof CompanyTypesRoute
  '/dashboard': typeof DashboardRoute
  '/diagnoses': typeof DiagnosesRoute
  '/docs': typeof DocsRoute
  '/doctors': typeof DoctorsRoute
  '/health': typeof HealthRoute
  '/hospitals': typeof HospitalsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/members': typeof MembersRoute
  '/reference-data': typeof ReferenceDataRoute
  '/register': typeof RegisterRoute
  '/reimbursements': typeof ReimbursementsRoute
  '/reports': typeof ReportsRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/tenants': typeof TenantsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banks'
    | '/billing-sessions'
    | '/card-replacements'
    | '/claim-payments'
    | '/claims'
    | '/companies'
    | '/company-branches'
    | '/company-groups'
    | '/company-types'
    | '/dashboard'
    | '/diagnoses'
    | '/docs'
    | '/doctors'
    | '/health'
    | '/hospitals'
    | '/labs'
    | '/login'
    | '/medicines'
    | '/members'
    | '/reference-data'
    | '/register'
    | '/reimbursements'
    | '/reports'
    | '/schemes'
    | '/services'
    | '/tenants'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banks'
    | '/billing-sessions'
    | '/card-replacements'
    | '/claim-payments'
    | '/claims'
    | '/companies'
    | '/company-branches'
    | '/company-groups'
    | '/company-types'
    | '/dashboard'
    | '/diagnoses'
    | '/docs'
    | '/doctors'
    | '/health'
    | '/hospitals'
    | '/labs'
    | '/login'
    | '/medicines'
    | '/members'
    | '/reference-data'
    | '/register'
    | '/reimbursements'
    | '/reports'
    | '/schemes'
    | '/services'
    | '/tenants'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/banks'
    | '/billing-sessions'
    | '/card-replacements'
    | '/claim-payments'
    | '/claims'
    | '/companies'
    | '/company-branches'
    | '/company-groups'
    | '/company-types'
    | '/dashboard'
    | '/diagnoses'
    | '/docs'
    | '/doctors'
    | '/health'
    | '/hospitals'
    | '/labs'
    | '/login'
    | '/medicines'
    | '/members'
    | '/reference-data'
    | '/register'
    | '/reimbursements'
    | '/reports'
    | '/schemes'
    | '/services'
    | '/tenants'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanksRoute: typeof BanksRoute
  BillingSessionsRoute: typeof BillingSessionsRoute
  CardReplacementsRoute: typeof CardReplacementsRoute
  ClaimPaymentsRoute: typeof ClaimPaymentsRoute
  ClaimsRoute: typeof ClaimsRoute
  CompaniesRoute: typeof CompaniesRoute
  CompanyBranchesRoute: typeof CompanyBranchesRoute
  CompanyGroupsRoute: typeof CompanyGroupsRoute
  CompanyTypesRoute: typeof CompanyTypesRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosesRoute: typeof DiagnosesRoute
  DocsRoute: typeof DocsRoute
  DoctorsRoute: typeof DoctorsRoute
  HealthRoute: typeof HealthRoute
  HospitalsRoute: typeof HospitalsRoute
  LabsRoute: typeof LabsRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRoute
  MembersRoute: typeof MembersRoute
  ReferenceDataRoute: typeof ReferenceDataRoute
  RegisterRoute: typeof RegisterRoute
  ReimbursementsRoute: typeof ReimbursementsRoute
  ReportsRoute: typeof ReportsRoute
  SchemesRoute: typeof SchemesRoute
  ServicesRoute: typeof ServicesRoute
  TenantsRoute: typeof TenantsRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursements': {
      id: '/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof ReimbursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference-data': {
      id: '/reference-data'
      path: '/reference-data'
      fullPath: '/reference-data'
      preLoaderRoute: typeof ReferenceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnoses': {
      id: '/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof DiagnosesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-types': {
      id: '/company-types'
      path: '/company-types'
      fullPath: '/company-types'
      preLoaderRoute: typeof CompanyTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-groups': {
      id: '/company-groups'
      path: '/company-groups'
      fullPath: '/company-groups'
      preLoaderRoute: typeof CompanyGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-branches': {
      id: '/company-branches'
      path: '/company-branches'
      fullPath: '/company-branches'
      preLoaderRoute: typeof CompanyBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-payments': {
      id: '/claim-payments'
      path: '/claim-payments'
      fullPath: '/claim-payments'
      preLoaderRoute: typeof ClaimPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-replacements': {
      id: '/card-replacements'
      path: '/card-replacements'
      fullPath: '/card-replacements'
      preLoaderRoute: typeof CardReplacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-sessions': {
      id: '/billing-sessions'
      path: '/billing-sessions'
      fullPath: '/billing-sessions'
      preLoaderRoute: typeof BillingSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanksRoute: BanksRoute,
  BillingSessionsRoute: BillingSessionsRoute,
  CardReplacementsRoute: CardReplacementsRoute,
  ClaimPaymentsRoute: ClaimPaymentsRoute,
  ClaimsRoute: ClaimsRoute,
  CompaniesRoute: CompaniesRoute,
  CompanyBranchesRoute: CompanyBranchesRoute,
  CompanyGroupsRoute: CompanyGroupsRoute,
  CompanyTypesRoute: CompanyTypesRoute,
  DashboardRoute: DashboardRoute,
  DiagnosesRoute: DiagnosesRoute,
  DocsRoute: DocsRoute,
  DoctorsRoute: DoctorsRoute,
  HealthRoute: HealthRoute,
  HospitalsRoute: HospitalsRoute,
  LabsRoute: LabsRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRoute,
  MembersRoute: MembersRoute,
  ReferenceDataRoute: ReferenceDataRoute,
  RegisterRoute: RegisterRoute,
  ReimbursementsRoute: ReimbursementsRoute,
  ReportsRoute: ReportsRoute,
  SchemesRoute: SchemesRoute,
  ServicesRoute: ServicesRoute,
  TenantsRoute: TenantsRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
